#!/usr/bin/env bash
#
# Generate CMB2 stubs from the vendor directory.
#
# @notice Must be run via PHP 7.4 or will be missing 1/3 of classes.
#
#
# Used via `%rootDir%/../../../stubs/cmb2/cmb2-2.9.php` under `scanFiles`.

PLUGIN_VERSION="2.10"

vendor/bin/generate-stubs \
--force \
--header="//Stubs generated by \`../stub-generators/cmb2.sh\`." \
--functions \
--classes \
--interfaces \
--traits \
--out=stubs/cmb2/cmb2-${PLUGIN_VERSION}.php \
./vendor/lipemat/cmb2/includes/
