#!/usr/bin/env bash
#
# Generate CMB2 stubs from the source directory.
#
# Used via `%rootDir%/../../../stubs/cmb2/cmb2-2.9.php` under `scanFiles`.

PLUGIN_VERSION="2.11"

dev/source/vendor/bin/generate-stubs \
--force \
--header="//Stubs generated by \`../stub-generators/cmb2.sh\`." \
--functions \
--classes \
--interfaces \
--traits \
--out=stubs/cmb2/cmb2-${PLUGIN_VERSION}.php \
./dev/source/vendor/lipemat/cmb2/includes/
