#!/usr/bin/env bash
#
# Generate Genesis stubs from the vendor directory.
#
# Used via `%rootDir%/../../../stubs/genesis/genesis-3.6.php` under `scanFiles`.

THEME_VERSION="3.6"

## @todo Switch to finder for exclude. See `generate-stubs --finder`.
Get_legacy_files() {
    echo "dev/source/vendor/lipemat/genesis/dev"
    echo "dev/source/vendor/lipemat/genesis/.idea"
    echo "dev/source/vendor/lipemat/genesis/.github"
    echo "dev/source/vendor/lipemat/genesis/.yarn"
}

# Delete excluded files
Get_legacy_files | xargs -- rm -v -r

dev/source/vendor/bin/generate-stubs \
    --force \
    --header="//Stubs generated by \`../stub-generators/genesis.sh\`." \
    --functions \
    --classes \
    --interfaces \
    --traits \
    --out=stubs/genesis/genesis-${THEME_VERSION}.php \
    ./dev/source/vendor/lipemat/genesis
