#!/usr/bin/env bash
#
# Generate Genesis stubs from the vendor directory.
#
# @note Must copy/paste genesis directory under vendor before running.
#       DO not include in GIT as is a premium theme!
#
# Used via `%rootDir%/../../../stubs/genesis/genesis-2.10.php` under `scanFiles`.

THEME_VERSION="3.3"

vendor/bin/generate-stubs \
    --force \
    --header="//Stubs generated by \`../stub-generators/genesis.sh\`." \
    --functions \
    --classes \
    --interfaces \
    --traits \
    --out=stubs/genesis/genesis-${THEME_VERSION}.php \
    ./vendor/genesis
