#!/usr/bin/env bash
#
# Generate Genesis stubs from the vendor directory.
#
# Used via `%rootDir%/../../../stubs/genesis/genesis-2.10.php` under `scanFiles`.

THEME_VERSION="3.5"

dev/source/vendor/bin/generate-stubs \
    --force \
    --header="//Stubs generated by \`../stub-generators/genesis.sh\`." \
    --functions \
    --classes \
    --interfaces \
    --traits \
    --out=stubs/genesis/genesis-${THEME_VERSION}.php \
    ./dev/source/vendor/lipemat/genesis
