#!/bin/bash
#
# Generate WooCommerce Subscriptions stubs from the vendor directory.
#
# @note Must copy/paste woocommerce-subscriptions directory under vendor before running.
#       DO not include in GIT as is a premium plugin!
#
# @notice Must be run via PHP 7.4 or will be missing 1/3 of classes.
#
# @example `bash dev/stub-generators/woocommerce-subscriptions.sh`
#
# Used via `%rootDir%/../../../stubs/woocommerce-subscriptions/woocommerce-subscriptions-4.7.php` under `scanFiles`.

PLUGIN_VERSION="5.0"

Get_legacy_files() {
    # Already in WC
    echo "vendor/woocommerce-subscriptions/woo-includes"
    # Legacy
    echo "vendor/woocommerce-subscriptions/includes/api/legacy"

    echo "vendor/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/legacy"
}

# Delete class files
Get_legacy_files | xargs -- rm -v -r

# @notice Must be run via PHP 7.4 or will be missing 1/3 of classes.
vendor/bin/generate-stubs \
    --force \
    --header="//Stubs generated by \`../stub-generators/woocommerce-subscriptions.sh\`." \
    --functions \
    --classes \
    --interfaces \
    --traits \
    --out=stubs/woocommerce-subscriptions/woocommerce-subscriptions-${PLUGIN_VERSION}.php \
    ./vendor/woocommerce-subscriptions
